// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.5.0.0
//      Runtime Version:4.0.30319.237
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
namespace Specs.Features.BookManagement
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.5.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Creating new books")]
    public partial class CreatingNewBooksFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "Creating.feature"
#line hidden
        
        [NUnit.Framework.TestFixtureSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Creating new books", "As the site owner\r\nI need to be able to create new books\r\nSo that I can show my o" +
                    "pinion of them", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.TestFixtureTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Valid Creation")]
        public virtual void ValidCreation()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Valid Creation", ((string[])(null)));
#line 6
this.ScenarioSetup(scenarioInfo);
#line 7
 testRunner.Given("I have navigated to the \"Create Book\" page");
#line 8
  testRunner.And("I have specified a title");
#line 9
  testRunner.And("I have specified a genre");
#line 10
  testRunner.And("I have specified a description");
#line 11
  testRunner.And("I have specified a status");
#line 12
  testRunner.And("I have specified at least one author");
#line 13
  testRunner.And("I have selected a cover image");
#line 14
 testRunner.When("I confirm creation");
#line 15
 testRunner.Then("I should be on the \"View Book\" page for the new book");
#line 16
  testRunner.And("I should see the title I entered");
#line 17
  testRunner.And("I should see the genre I entered");
#line 18
  testRunner.And("I should see the description I entered");
#line 19
  testRunner.And("I should the status I entered");
#line 20
  testRunner.And("I should see the author(s) I entered");
#line 21
  testRunner.And("I should see the cover image I selected");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Invalid Input")]
        public virtual void InvalidInput()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Invalid Input", ((string[])(null)));
#line 23
this.ScenarioSetup(scenarioInfo);
#line 24
 testRunner.Given("I have navigated to the \"Create Book\" page");
#line 25
  testRunner.And("I have not entered any information");
#line 26
 testRunner.When("I confirm creation");
#line 27
 testRunner.Then("I should be on the \"Create Book\" page");
#line 28
  testRunner.And("I should see a failed validation message for each empty field");
#line hidden
            testRunner.CollectScenarioErrors();
        }
    }
}
#endregion
